package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/yuin/goldmark"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	gmhtml "github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
)

// codeBlockInfo stores line numbers for a code block
type codeBlockInfo struct {
	startLine int
	endLine   int
}

// LineAttributeTransformer collects line numbers for all block nodes
type LineAttributeTransformer struct {
	codeBlocks []*codeBlockInfo
}

func (t *LineAttributeTransformer) Transform(doc *ast.Document, reader text.Reader, pc parser.Context) {
	source := reader.Source()
	t.codeBlocks = nil // Reset for each document

	_ = ast.Walk(doc, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}

		// Only process block-level nodes
		if node.Type() == ast.TypeBlock {
			// Skip list containers (ul/ol) - their children (li) will have attributes
			if node.Kind() == ast.KindList {
				return ast.WalkContinue, nil
			}

			var startLine, endLine int

			// Special handling for FencedCodeBlock to include the opening fence line
			if node.Kind() == ast.KindFencedCodeBlock {
				fcb := node.(*ast.FencedCodeBlock)
				// Use the Info segment to find the opening fence line
				if fcb.Info != nil {
					infoStart := fcb.Info.Segment.Start
					startLine = bytes.Count(source[:infoStart], []byte{'\n'}) + 1
				} else {
					// No info, use first line of content
					if fcb.Lines().Len() > 0 {
						firstLine := fcb.Lines().At(0)
						// The opening fence is on the line before the first content line
						startLine = bytes.Count(source[:firstLine.Start], []byte{'\n'})
					}
				}

				// End line is after the last content line (includes closing fence)
				if fcb.Lines().Len() > 0 {
					lastLine := fcb.Lines().At(fcb.Lines().Len() - 1)
					endLine = bytes.Count(source[:lastLine.Stop], []byte{'\n'}) + 1
					// Add 1 for the closing fence line
					endLine++
				}

				// Store code block info for post-processing
				t.codeBlocks = append(t.codeBlocks, &codeBlockInfo{
					startLine: startLine,
					endLine:   endLine,
				})
			} else {
				lines := node.Lines()

				if lines.Len() > 0 {
					// Node has direct line info
					firstLine := lines.At(0)
					startLine = bytes.Count(source[:firstLine.Start], []byte{'\n'}) + 1

					lastLine := lines.At(lines.Len() - 1)
					endLine = bytes.Count(source[:lastLine.Stop], []byte{'\n'}) + 1
				} else {
					// Node has no direct line info
					// Calculate from children
					startLine, endLine = getChildLineRange(node, source)
					if startLine == 0 {
						// No line info available from children either
						return ast.WalkContinue, nil
					}
				}
			}

			// Set attributes (goldmark's HTML renderer will automatically render them for non-code blocks)
			node.SetAttribute([]byte("data-line-start"), []byte(strconv.Itoa(startLine)))
			node.SetAttribute([]byte("data-line-end"), []byte(strconv.Itoa(endLine)))
		}

		return ast.WalkContinue, nil
	})
}

// getChildLineRange calculates line range from a node's children
func getChildLineRange(node ast.Node, source []byte) (int, int) {
	var startLine, endLine int

	// Walk children to find first and last line numbers
	for child := node.FirstChild(); child != nil; child = child.NextSibling() {
		lines := child.Lines()
		if lines.Len() > 0 {
			firstLine := lines.At(0)
			childStart := bytes.Count(source[:firstLine.Start], []byte{'\n'}) + 1

			lastLine := lines.At(lines.Len() - 1)
			childEnd := bytes.Count(source[:lastLine.Stop], []byte{'\n'}) + 1

			if startLine == 0 || childStart < startLine {
				startLine = childStart
			}
			if childEnd > endLine {
				endLine = childEnd
			}
		} else {
			// Recursively check grandchildren
			childStart, childEnd := getChildLineRange(child, source)
			if childStart > 0 {
				if startLine == 0 || childStart < startLine {
					startLine = childStart
				}
				if childEnd > endLine {
					endLine = childEnd
				}
			}
		}
	}

	return startLine, endLine
}

// LineAttributeExtension is a goldmark extension that adds line number attributes
type LineAttributeExtension struct {
	transformer *LineAttributeTransformer
}

func (e *LineAttributeExtension) Extend(m goldmark.Markdown) {
	m.Parser().AddOptions(
		parser.WithASTTransformers(
			util.Prioritized(e.transformer, 100),
		),
	)
}

// addLineAttributesToCodeBlocks post-processes HTML to add data-line-* attributes to <pre> tags
// generated by Chroma. This allows us to use Chroma's default rendering while still adding
// our custom line tracking attributes.
func addLineAttributesToCodeBlocks(html []byte, codeBlocks []*codeBlockInfo) []byte {
	// Match <pre> tags (may have style attribute from Chroma)
	re := regexp.MustCompile(`<pre([^>]*)>`)
	blockIndex := 0

	result := re.ReplaceAllFunc(html, func(match []byte) []byte {
		if blockIndex >= len(codeBlocks) {
			// Not a code block (or we've run out of tracked blocks), return as-is
			return match
		}

		block := codeBlocks[blockIndex]
		blockIndex++

		// Extract existing attributes (e.g., style="background-color:#f0f0f0;")
		existingAttrs := string(match[4 : len(match)-1])

		// Add our custom attributes at the beginning
		return []byte(fmt.Sprintf(`<pre data-line-start="%d" data-line-end="%d"%s>`,
			block.startLine, block.endLine, existingAttrs))
	})

	return result
}

// RenderMarkdownWithLineNumbers renders markdown to HTML with line number attributes
func RenderMarkdownWithLineNumbers(source []byte) ([]byte, error) {
	transformer := &LineAttributeTransformer{}

	md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			&LineAttributeExtension{transformer: transformer},
			highlighting.NewHighlighting(
				highlighting.WithStyle("friendly"),
			),
		),
		goldmark.WithRendererOptions(
			gmhtml.WithUnsafe(), // Allow raw HTML
		),
	)

	var buf bytes.Buffer
	if err := md.Convert(source, &buf); err != nil {
		return nil, err
	}

	// Post-process HTML to add data-line-* attributes to code blocks
	html := addLineAttributesToCodeBlocks(buf.Bytes(), transformer.codeBlocks)

	return html, nil
}

// Truncation thresholds for quoted ranges in chat output (per the inline
// annotation spec: render first 2 lines, "> …", last 2 lines, when a range
// exceeds either limit).
const (
	chatQuoteMaxLines = 6
	chatQuoteMaxChars = 400
	chatHeadTailLines = 2
)

// chatThread is one render-ready annotation block: zero-or-more quoted ranges
// (the root selection plus any multi-select extras) followed by the user's
// verb + comment.
type chatThread struct {
	ranges    []chatRange
	verb      string // "agree" | "reject" | "question" | "comment" | ""
	body      string // free-form text (optional reason for agree/reject; required for ?/c)
	firstLine int    // smallest line across ranges, for document-order sort
}

type chatRange struct {
	lineStart    int
	lineEnd      int
	selectedText string
}

// RenderThreadsToChat takes the original scratch markdown plus the threads
// the user attached to it, and returns a single compact reply suitable for
// pasting back to an agent. Threads are emitted in document order; untouched
// parts of the source are NOT included (the agent already has them).
//
// The `source` parameter is currently unused but accepted to keep the API
// stable as future renderers may need it (e.g. to reflow selections by line
// number when SelectedText is empty).
func RenderThreadsToChat(_ string, threads [][]Comment) string {
	chatThreads := make([]chatThread, 0, len(threads))
	for _, t := range threads {
		ct, ok := buildChatThread(t)
		if ok {
			chatThreads = append(chatThreads, ct)
		}
	}

	// Stable sort by first line across all attached ranges.
	for i := 0; i < len(chatThreads); i++ {
		for j := i + 1; j < len(chatThreads); j++ {
			if chatThreads[j].firstLine < chatThreads[i].firstLine {
				chatThreads[i], chatThreads[j] = chatThreads[j], chatThreads[i]
			}
		}
	}

	blocks := make([]string, 0, len(chatThreads))
	for _, ct := range chatThreads {
		blocks = append(blocks, renderChatThread(ct))
	}
	return strings.Join(blocks, "\n\n")
}

func buildChatThread(thread []Comment) (chatThread, bool) {
	if len(thread) == 0 {
		return chatThread{}, false
	}
	root := thread[0]

	ranges := []chatRange{}
	if root.SelectedText != "" {
		ranges = append(ranges, chatRange{
			lineStart:    intOrZero(root.LineStart),
			lineEnd:      intOrZero(root.LineEnd),
			selectedText: root.SelectedText,
		})
	}
	if root.ExtraRanges != "" {
		var extras []ExtraRange
		if err := json.Unmarshal([]byte(root.ExtraRanges), &extras); err == nil {
			for _, e := range extras {
				ranges = append(ranges, chatRange{
					lineStart:    e.LineStart,
					lineEnd:      e.LineEnd,
					selectedText: e.SelectedText,
				})
			}
		}
	}

	// Sort ranges within a thread by line number so multi-select reads top-to-bottom.
	for i := 0; i < len(ranges); i++ {
		for j := i + 1; j < len(ranges); j++ {
			if ranges[j].lineStart < ranges[i].lineStart {
				ranges[i], ranges[j] = ranges[j], ranges[i]
			}
		}
	}

	firstLine := 1 << 30
	for _, r := range ranges {
		if r.lineStart > 0 && r.lineStart < firstLine {
			firstLine = r.lineStart
		}
	}
	if firstLine == 1<<30 {
		firstLine = 0
	}

	return chatThread{
		ranges:    ranges,
		verb:      root.Verb,
		body:      strings.TrimSpace(root.CommentText),
		firstLine: firstLine,
	}, true
}

func renderChatThread(ct chatThread) string {
	var b strings.Builder
	for i, r := range ct.ranges {
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(renderQuotedRange(r.selectedText))
	}
	if len(ct.ranges) > 0 {
		b.WriteString("\n\n")
	}
	b.WriteString(renderVerbResponse(ct.verb, ct.body))
	return b.String()
}

// renderQuotedRange emits a `> ` quoted block, applying central-ellipsis
// truncation when the selection exceeds chatQuoteMaxLines OR chatQuoteMaxChars.
func renderQuotedRange(text string) string {
	text = strings.TrimRight(text, "\n")
	lines := strings.Split(text, "\n")

	truncate := len(lines) > chatQuoteMaxLines || len(text) > chatQuoteMaxChars
	if !truncate {
		return prefixQuote(lines)
	}

	head := lines[:chatHeadTailLines]
	tail := lines[len(lines)-chatHeadTailLines:]
	// Guard against overlap on borderline inputs.
	if len(lines) < 2*chatHeadTailLines {
		return prefixQuote(lines)
	}

	combined := append([]string{}, head...)
	combined = append(combined, "…")
	combined = append(combined, tail...)
	return prefixQuote(combined)
}

func prefixQuote(lines []string) string {
	out := make([]string, 0, len(lines))
	for _, l := range lines {
		if l == "" {
			out = append(out, ">")
		} else {
			out = append(out, "> "+l)
		}
	}
	return strings.Join(out, "\n")
}

func renderVerbResponse(verb, body string) string {
	body = strings.TrimSpace(body)
	switch verb {
	case "agree":
		if body != "" {
			return "Agreed. " + body
		}
		return "Agreed."
	case "reject":
		if body != "" {
			return "Skip. " + body
		}
		return "Skip."
	case "question":
		if body == "" {
			return "Q:"
		}
		return "Q: " + body
	default:
		// "comment" or empty verb — emit body verbatim. Body may be empty for
		// degenerate cases (e.g. a stray empty comment); skip empty output.
		if body == "" {
			return ""
		}
		return body
	}
}

func intOrZero(p *int) int {
	if p == nil {
		return 0
	}
	return *p
}

// RenderThreadsToDirective returns the thread-reply directive that Claude
// Code interprets when the user presses ⌥↩ ("Send & Continue") in the browser.
// Instead of the single-shot chat blob, each thread is emitted with its ID so
// the agent can call `claude-review reply --comment-id N` per thread and let
// the browser display replies inline via SSE. When threads is empty, a
// no-op directive is emitted that just tells the agent to loop back into
// /annotate resume=<sessionID>.
func RenderThreadsToDirective(sessionID string, threads [][]Comment) string {
	var b strings.Builder
	fmt.Fprintf(&b, "You have unread annotations from the user in claude-review scratch session `%s`.\n\n", sessionID)
	if len(threads) == 0 {
		b.WriteString("Nothing new since last sync; no per-thread replies needed.\n\n")
		fmt.Fprintf(&b, "Invoke `/annotate resume=%s` to keep the review open for the next round.\n", sessionID)
		return b.String()
	}

	b.WriteString("Reply to each thread individually with:\n")
	b.WriteString("    claude-review reply --comment-id <ID> --message \"<your reply>\"\n\n")
	b.WriteString("Do NOT respond in the terminal chat — the browser is the source of truth; the\n")
	b.WriteString("user is watching threads populate live via SSE.\n\n")
	b.WriteString("Threads awaiting your reply:\n\n")

	for i, thread := range threads {
		if len(thread) == 0 {
			continue
		}
		root := thread[0]
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "─── thread %d ──────────────────────────────────────────────\n", root.ID)
		b.WriteString(renderDirectiveThreadBody(thread))
	}

	b.WriteString("\n")
	fmt.Fprintf(&b, "When all thread replies are posted, invoke `/annotate resume=%s` to\n", sessionID)
	b.WriteString("keep the review open for the next round.\n")
	return b.String()
}

// renderDirectiveThreadBody emits the Selection: quote followed by the most
// recent user message in the thread. Prior user messages have already been
// forwarded on earlier rounds, so we only surface what's new. The intro
// ("User said:" / "User asked:") is verb-aware so the agent has a hint about
// tone before it drafts a reply.
func renderDirectiveThreadBody(thread []Comment) string {
	root := thread[0]

	var b strings.Builder
	b.WriteString("Selection:\n")

	ranges := []chatRange{}
	if root.SelectedText != "" {
		ranges = append(ranges, chatRange{
			lineStart:    intOrZero(root.LineStart),
			lineEnd:      intOrZero(root.LineEnd),
			selectedText: root.SelectedText,
		})
	}
	if root.ExtraRanges != "" {
		var extras []ExtraRange
		if err := json.Unmarshal([]byte(root.ExtraRanges), &extras); err == nil {
			for _, e := range extras {
				ranges = append(ranges, chatRange{
					lineStart:    e.LineStart,
					lineEnd:      e.LineEnd,
					selectedText: e.SelectedText,
				})
			}
		}
	}
	for i, r := range ranges {
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(renderQuotedRange(r.selectedText))
	}
	if len(ranges) > 0 {
		b.WriteString("\n")
	}

	// Find the most recent user message: prefer the last user-authored
	// reply, else fall back to the root itself.
	var latest *Comment
	for i := len(thread) - 1; i >= 0; i-- {
		if thread[i].Author == "user" {
			c := thread[i]
			latest = &c
			break
		}
	}
	if latest == nil {
		// Should not happen — the delta filter guarantees at least one
		// user comment — but guard anyway.
		latest = &root
	}

	verb := ""
	if latest.ID == root.ID {
		verb = root.Verb
	}
	body := strings.TrimSpace(latest.CommentText)

	intro := "User said:"
	switch verb {
	case "question":
		intro = "User asked:"
	case "reject":
		intro = "User rejected:"
	case "agree":
		intro = "User agreed:"
	}

	rendered := renderVerbResponse(verb, body)
	if rendered == "" {
		rendered = body
	}
	fmt.Fprintf(&b, "%s %s\n", intro, rendered)
	return b.String()
}

// RenderMarkdown renders markdown to HTML without line number attributes
func RenderMarkdown(source []byte) ([]byte, error) {
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			highlighting.NewHighlighting(
				highlighting.WithStyle("friendly"),
			),
		),
		goldmark.WithRendererOptions(
			gmhtml.WithUnsafe(), // Allow raw HTML
		),
	)

	var buf bytes.Buffer
	if err := md.Convert(source, &buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
